//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandLord_ROR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandNature
    {
        public int SNo { get; set; }
        public string LandNatureCode { get; set; }
        public string LandNatureName { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string Modifiedby { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
