//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandLord_ROR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MILESTATESEntities : DbContext
    {
        public MILESTATESEntities()
            : base("name=MILESTATESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LandLord> LandLords { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Mandal> Mandals { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<LandZone> LandZones { get; set; }
        public virtual DbSet<LandNature> LandNatures { get; set; }
        public virtual DbSet<Spl_Category> Spl_Category { get; set; }
        public virtual DbSet<Land_Title_Type_Master> Land_Title_Type_Master { get; set; }
        public virtual DbSet<LandLordROR> LandLordRORs { get; set; }
    }
}
