//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandLord_ROR
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandLordROR
    {
        public int SNo { get; set; }
        public string VillageCd { get; set; }
        public string MandalCd { get; set; }
        public string DistrictCd { get; set; }
        public string StateCd { get; set; }
        public string SurveyNo { get; set; }
        public string LandLordCode { get; set; }
        public string LandZoneCode { get; set; }
        public string LandTitleCode { get; set; }
        public string OwnerShipType { get; set; }
        public string LandNatureCode { get; set; }
        public string Doc_No { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
       
        public string PT { get; set; }
        public string PT_Details { get; set; }
        public string Land_Conversion { get; set; }
        public Nullable<decimal> Extent_Acres { get; set; }
        public Nullable<decimal> Extent_Guntas { get; set; }
        public Nullable<decimal> Extent_Sqyds { get; set; }
        public Nullable<decimal> TotalExtent_Acres { get; set; }
        public Nullable<decimal> TotalExtent_Guntas { get; set; }
        public Nullable<decimal> TotalExtent_Sqyds { get; set; }
        public string LL_PassbookNo { get; set; }
        public string ProceedingNo { get; set; }
        public string Spl_Category { get; set; }
        public string SurveyNo_SubLetter { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string PurchaseType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> LL_Extent_Acres { get; set; }
        public Nullable<decimal> LL_Extent_Guntas { get; set; }
        public Nullable<decimal> LL_Extent_Sqyds { get; set; }
    
        public virtual LandLord LandLord { get; set; }
    }
}
