//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandLord_ROR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public int VillageId { get; set; }
        public string VillageCd { get; set; }
        public string VillageName { get; set; }
        public string MandalCd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Mandal Mandal { get; set; }
    }
}
