<%--<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="LandLord_ROR.WebForm1" %>--%>
<%@ Page Language="C#" MasterPageFile="~/Site.Master" %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    



    <%-- <script src="Scripts/jquery-1.12.4.min.js"></script>
    <script src="Scripts/jquery-ui.min.js"></script>
    <link href="Content/jquery-ui.min.css" rel="stylesheet" />
    <script src="Scripts/MicrosoftAjax.js"></script>
    <script src="Scripts/MicrosoftMvcAjax.js"></script>
    <script src="Scripts/AjaxControlToolkit/AjaxControlToolkit.js"></script>--%>
</head>
<body>
   
    <%-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Modal Title</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Modal Content
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>




   
    <form id="form1" runat="server">
        <div>
            <asp:Table ID="Table1" runat="server" CellPadding="2" CellSpacing="2" Border="0" style="width:100%" Align="center">
              <asp:TableRow style="background-color:cadetblue">
                  <asp:TableCell ColumnSpan="2"><h2>Land Lord ROR</h2></asp:TableCell></asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell ColumnSpan="6">
                        <hr />
                    </asp:TableCell>
                </asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell ColumnSpan="2">
                        <span class="lable1" style="color:blue" >* LandLord</span>
                         </asp:TableCell>
                    <asp:TableCell ColumnSpan="2">
                        <span class="lable2" style="color:blue">TotalExtent</span>
                        </asp:TableCell>
                    <asp:TableCell ColumnSpan="2">
                        <span class="lable3" style="color:blue">Procured&Balance</span>
                    </asp:TableCell>
                </asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell ColumnSpan="2">
                         <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox><asp:DropDownList ID="DropDownList1" runat="server" placeholder="LandLord1" style="width:200px;"></asp:DropDownList>
                         </asp:TableCell>
                     <asp:TableCell ColumnSpan="2">
                         <span class="label4" style="width:100px;font-size:12px; display:inline-block">Acres</span>
                         <span class="label4" style="width:100px;font-size:12px; display:inline-block">Guntas</span>
                         <span class="label4" style="width:100px;font-size:12px; display:inline-block">Sq.Ads</span>
                         <br />
                          <asp:TextBox ID="TextBox2" runat="server" style="width:97px;text-align:right;margin-bottom:6px;" placeholder="Acres"></asp:TextBox>
                          <asp:TextBox ID="TextBox3" runat="server" style="width:97px;text-align:right;" placeholder="Guntas"></asp:TextBox>
                          <asp:TextBox ID="TextBox4" runat="server" style="width:97px;text-align:right;" placeholder="Sq.Ads"></asp:TextBox>
                         </asp:TableCell>
                    <asp:TableCell>
                        <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox> <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox> 
                    </asp:TableCell>
                    </asp:TableRow>
                <asp:TableRow>
                    <asp:TableCell ColumnSpan="4" >
                        <asp:Button ID="Button1" runat="server" Text="Button" data-toggle="modal" data-target="#myModal" />
                    </asp:TableCell>
                </asp:TableRow>
            </asp:Table>

           <asp:GridView runat="server" ID="LandLordGrid"
  AutoGenerateDeleteButton="true"  
    AutoGenerateColumns="false">
                <Columns>
        <asp:BoundField DataField="LandLordCode"  HeaderText="LandLord" /> 
        <asp:BoundField DataField="SurveyNo" HeaderText="SurveyNo" />
        <asp:BoundField DataField="SurveyNo_SubLetter" HeaderText="SubLetter" />  
        <asp:BoundField DataField="Extent_Acres" HeaderText="Acres" />  
        <asp:BoundField DataField="Extent_Guntas" HeaderText="Guntas" />  
        <asp:BoundField DataField="Extent_Sqyds" HeaderText="Sqyds" />  
        <asp:BoundField DataField="Doc_No" HeaderText="DoccumentNo" />  
    </Columns>
           </asp:GridView>
        </div>
         <div>
         
        </div>
    </form>
    <script type="text/javascript">
    $(document).ready(function () {
        $('#myModal').modal('hide'); // Hide the modal on page load
    });

    function openModal() {
        $('#myModal').modal('show'); // Show the modal when the button is clicked
    }
</script>--%>
        
</body>
    
</html>
